# Default values for starthelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: myreg.com/login-api
  tag: 1.0.7
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  MONGO_DB_LOGIN_API: mongodb://admin:passw0rd@169.56.164.245:27017/db-users
  JWT_SECRET: MySecretKey
  TOKEN_EXPIRE_TIME: 21600
  
service:
  type: ClusterIP
  port: 3001
  externalIPs:  [ "169.56.164.245", "169.56.164.244", "169.56.164.254" ]

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: login-api.169.56.164.254.nip.io
      paths: [ "/" ]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

########## dependency charts #########
mongodb:
  enabled: true
  mongodbRootPassword: passw0rd
  db:
    name: db-users
    collection: users    
    adminUser: dbadmin
    adminPassword: passw0rd
    nodeUser: admin
    nodePassword: passw0rd
  service:
    type: ClusterIP
    port: 27017
    externalIPs: [ "169.56.164.245", "169.56.164.244", "169.56.164.254" ]
  ingress:
    enabled: false
  persistence:
    nfs:
      server: 169.56.164.245
      path: /data/nfs/mongodb-login-api
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
